# Generated by Django 4.2.5 on 2023-09-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(choices=[('DE', 'Developer'), ('MA', 'Manager'), ('AN', 'Analist'), ('TE', 'Tester'), ('SU', 'Support')], default='DE', max_length=2)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_admissao', models.DateField()),
                ('active', models.BooleanField(default=1)),
            ],
        ),
    ]
