# Generated by Django 4.2.5 on 2023-09-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='data_admissao',
            new_name='admission',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salario',
            new_name='salary',
        ),
    ]
